[Feature] Change settings object
codex-team/codex-accounting-sdk pull request #3
Opened 2020-09-17 13:16 UTC by ilyamore88

Use a new pattern for TLS verification settings. Closes #2.

2020-09-17 13:25 UTC, neSpecc approved these changes

2020-09-17 13:48 UTC, talyguryn requested changes

2020-09-17 13:48 UTC, talyguryn commented on client.ts
> +        ca: fs.readFileSync(settings.tlsVerify.tlsCaCertPath),
не нужно ли добавить тут проверки на пустоту этих трех полей?

2020-09-25 13:30 UTC, nikmel2803 approved these changes

2020-09-25 17:01 UTC, talyguryn approved these changes

2020-09-25 17:05 UTC, merged